### PR TITLE
feat(web/radial): Add event and serverEvent option to item click

### PR DESCRIPTION
**Pull request by Moozdzn**
Allows the same flexibility of choice that already exists in context menu

### CODE REVIEW

**Comment by LukeWasTakenn** [comment]
Just use `onSelect` to run the events.

**Comment by Moozdzn** [comment]
Any reason for this feature to be present in context menu but not the radial?

**Comment by thelindat** [comment]
Stuff like this should trigger a specific action - if an event is wanted it can be fired after that. People tend to have weird design choices when given more flexibility, such as needing an "args" table on _everything_ even though it's a bunch of pre-defined _static_ data that could be defined locally in your resource, wherever it gets used.

If we could go back and remove support for these things we would, but we've tried that before and the amount of complaints is astounding.

**Comment by Moozdzn** [comment]
I wondered if it was something like that but decided to make a PR just in case. Fair enough, thank you for the explanation

**Pull request closed without merging**
