### PR TITLE
feat(interface/dialog): readonly, disabled flags

### PR DESCRIPTION
**Pull request by davidxd33**
This adds support for making fields disabled or read only.

### CODE REVIEW

**Comment by LukeWasTakenn** [comment]
Are readonly and disabled not kind of the same thing?

**Comment by davidxd33** [comment]
> Are readonly and disabled not kind of the same thing?

One greys it out and changes the cursor, the other just makes it "uninteractable" while looking normal.

**Review by LukeWasTakenn — CHANGES_REQUESTED** [review]
The TS types in the package should also be updated, and could you also make a PR to the docs?

**Comment by davidxd33** [comment]
> Member

Done

**Review by LukeWasTakenn — APPROVED** [review]
Removed read only property because I can already see people complaining that it's not working even though it's the intended behavior.

**Pull request merged**
