### PR TITLE
Add step property to NumberInput.

### PR DESCRIPTION
**Pull request by Lunar-Scripts**
Added a missing property for NumberInput.

### CODE REVIEW

**Review by LukeWasTakenn — COMMENTED** [review]
Step really doesn't do much unless you're using the scroll wheel or increment/decrement controls to change the value so not really sure how useful this actually is?

**Comment by Lunar-Scripts** [comment]
The default step value isn't suitable for all situations when using the increment/decrement controls.
I am sure some people will find this useful too.

**Review by LukeWasTakenn — APPROVED** [review]
Can you add the change to the docs as well?

**Comment by Lunar-Scripts** [comment]
Sure, no problem: [https://github.com/overextended/overextended.github.io/pull/151](PR)

**Review by LukeWasTakenn — APPROVED** [review]

**Pull request merged**
