### PR TITLE
feat(resource/vehicleProperties/client.lua): adding a configuration for plate format

### PR DESCRIPTION
**Pull request by HR0110**
…ace at the end of the plate value that breaks the value matchings

### CODE REVIEW

**Comment by CeebDev** [comment]
If you use plate format with 7 digits instead 8 it's not the case for all users.

ox_lib just need to handle plate with what GTA return

**Comment by HR0110** [comment]
> If you use plate format with 7 digits instead 8 it's not the case for all users.
> 
> ox_lib just need to handle plate with what GTA return

Yes I know, just forgotten to commit the part with a configuration for a 7 bits plates or 8 bits because the 7 bits format is very popular and makes many issues when trying to match with a plate text. I'm gonna do it. Thank you!

**Comment by thelindat** [comment]
This is stupid and so incredibly breaking.

> the 7 bits format is very popular

That doesn't change the fact that GTAV vehicle plates are _always_ 8 characters long. Either trim the whitespace in the plate, or pad the comparison. _In your own code._

**Comment by HR0110** [comment]
> This is stupid and so incredibly breaking.
> 
> > the 7 bits format is very popular
> 
> That doesn't change the fact that GTAV vehicle plates are _always_ 8 characters long. Either trim the whitespace in the plate, or pad the comparison. _In your own code._

The idea is that ox_lib can cut the plates according to the user's preference directly from it, rather than having to use ox_core for this purpose

**Pull request closed without merging**
