### PR TITLE
fix(client/vehicleproperties): extras & fix(web): heading props

### PR DESCRIPTION
**Pull request by jellyton69**
Vehicle Properties: When using `SetVehicleAutoRepairDisabled`, you need to repair the vehicle for applied extras to be visible.

Interface: Fixed weird heading margins when using markdown heading props.
August06 - 03 24 - 2641

Sorry for 2 commits per pull, I couldn't figure out how to separate them.

### CODE REVIEW

**Comment by thelindat** [comment]
Preferred unrelated commits go in separate PRs.

---

Users can just pass SetVehicleFixed themselves, or otherwise add an arg to fix the vehicle?

**Review by LukeWasTakenn — CHANGES_REQUESTED** [review]
> Sorry for 2 commits per pull, I couldn't figure out how to separate them.

Cherry pick the commits onto separate branches then open a PR from each of the branches to master.

`markdowncomponents.tsx` file should follow the naming convention so far, `MarkdownComponents.tsx`

**Comment by jellyton69** [comment]
> Cherry pick the commits onto separate branches then open a PR from each of the branches to master.

Alrighty I'll close this, fix the requested changes and reopen it with separate pulls.

**Comment by jellyton69** [comment]
> Users can just use SetVehicleFixed themselves, or otherwise add an arg to fix the vehicle?

Would you rather it be a new value in the props table, or an extra param in the setVehicleProperties function?

**Comment by thelindat** [comment]
Just a new function arg.

**Pull request closed without merging**
