### PR TITLE
feat(logger/loki): Allow users to specify protocol for requests

### PR DESCRIPTION
**Pull request by TheiLLeniumStudios**
This is helpful for simple environments which don't have SSL enabled
- Defaults to `https`

### CODE REVIEW

**Comment by ahcenezdh** [comment]
You should allow user to not use a password too, since loki can be used without a password

**Comment by thelindat** [comment]
endpoint should rather support the full address (prepending https if no protocol is included).

**Comment by TheiLLeniumStudios** [comment]
@thelindat should I then remove the user and password vars as well? Since those need to be part of the URL? Users will then need to provide it as part of the URL as well. Because if I don't, then I'll have to split the URL up just to extract the protocol from it and recreate the full URL

**Comment by thelindat** [comment]
Nothing wrong with splitting up the string but right now the convars are a bit of a mess and certain things are hardcoded which shouldn't be. Well, whatever works for you - I don't and haven't used Loki; logger itself needs a rewrite so right now easiest solutions are best.

**Comment by TheiLLeniumStudios** [comment]
Well, another way would be to use a Basic Auth authorization header instead of appending the credentials in the URL. I will play around with it and update the P

**Comment by TheiLLeniumStudios** [comment]
@thelindat can you take a look again please?

**Pull request merged**
