### PR TITLE
Add cache.vehiclecam for Vehicle Cam View Mode

### PR DESCRIPTION
**Pull request by nurrifqialhusaini**
Hello, i wanna make vehicle cam for easy check vehicle cam view mode
I hope this can be useful on ox lib

### CODE REVIEW

**Review by badfantomasss — CHANGES_REQUESTED** [review]
On line 15 add this:
local GetFollowVehicleCamViewMode = GetFollowVehicleCamViewMode

On line 26 add this:
local vehicleCam = GetFollowVehicleCamViewMode()

and edit cache:set('vehiclecam', GetFollowVehicleCamViewMode()) to cache:set('vehiclecam', vehicleCam)

**Comment by nurrifqialhusaini** [comment]
lets try

**Comment by badfantomasss** [comment]
and probably change vehiclecam to vehicleCam... Ox use this coding style

**Comment by thelindat** [comment]
cache is generally for things that don't update frequently, are referenced by scripts often, and referenced by many scripts.
I don't see vehicle cam being useful in more than one or _maybe_ two scripts?

**Comment by nurrifqialhusaini** [comment]
vehicle cam useful for someone make only "fpp mode" to access some func, maybe some people will use it

**Comment by thelindat** [comment]
> vehicle cam useful for someone make only "fpp mode" to access some func, maybe some people will use it

Still not seeing this as useful in more than a couple scripts, which can just run their own loop anyway.

**Comment by nurrifqialhusaini** [comment]
alright, ill close this pull

**Pull request closed without merging**
