### PR TITLE
feat(client/cache): adds cached 'dead' status of a player

### PR DESCRIPTION
**Pull request by 0xDEMXN**

### CODE REVIEW

**Comment by jag3dagster** [comment]
Would this even work? Don't most cores revive the player and have them play a 'downed' animation instead of leaving them actually dead?

**Comment by 0xDEMXN** [comment]
> Would this even work? Don't most cores revive the player and have them play a 'downed' animation instead of leaving them actually dead?

I mean, do we care?
Not everyone use that death system and imo this could be just useful for many people.

**Comment by jag3dagster** [comment]
> I mean, do we care?

Yes because we'll have to deal with all of the support questions about "Why isn't this working?"

I don't think it's a bad feature, I just think the implementation doesn't cover the majority of cases, or at least handles them in a confusing way.

**Comment by 0xDEMXN** [comment]
> > I mean, do we care?
> 
> Yes because we'll have to deal with all of the support questions about "Why isn't this working?"
> 
> I don't think it's a bad feature, I just think the implementation doesn't cover the majority of cases, or at least handles them in a confusing way.

Well if the player is revived and put down he's not dead so the "dead" value will be correct anyway.

**Comment by 0xDEMXN** [comment]
Also I don't see a lot of servers using that system (at least in my country).

**Comment by thelindat** [comment]
No. Death systems are more complicated than setting a dead value, so this is useless with every known framework anyway.

**Pull request closed without merging**
