### PR TITLE
Fixed attempt to compare number with nil

### PR DESCRIPTION
**Pull request by mindiw01**

### CODE REVIEW

**Comment by mindiw01** [comment]
https://i.imgur.com/xEY0Gsz.png

**Comment by mindiw01** [comment]
FiveM_b2372_GTAProcess_oBFNxynmyL

**Comment by DokaDoka** [comment]
what input produced this error?

**Comment by mindiw01** [comment]
I have many zones created, I could not verify which was the input that produced this error. I attach the zone that gave the problem and how I craeted them:

```
	[16] = {
		['zone'] = {
			['type'] = 'sphere', -- avaiable types: box, sphere, poly
			['thickness'] = 200.0,
			['debug'] = false,
			-- if a sphere zone
			['radius'] = 75.0,
			-- if a box zone
			['size'] = vec3(1, 1, 1),
			['rotation'] = 45.0,
			['typezone'] = 'robbery-zone-civil',
			['coords'] = {
				vec3(-1068.73, -2562.11, 53.17),
			},
			['action'] = {
				onEnter = function(self)
					OnEnterRobberyZone(self)
					exports['mythic_notify']:PersistentAlert('start', 'robberyZoneAlert', 'error', '¡Estás en una Zona de Robo/Tiroteo/Secuestro!')
				end,
				onExit = function(self)
					ExitRobberyZone(self)
				end,
				inside = function(self)
					InsideRobberyZone(self)
				end,
			},
		},
		['blip'] = {
			['blip_radius'] = {
				['enabled'] = true,
				['coords'] = {
					['X'] = -1068.73, ['Y'] =  -2562.11, ['Z'] = 54.17,
				},
				['color'] = 33,
				['radius'] = 75.0,
				['alpha'] = 70,
			},
			['blip_marker'] = {
				['enabled'] = false,
				['coords'] = {
					['X'] = 255.250198, ['Y'] = 226.070358, ['Z'] = 101.882225,
				},
				['color'] = 0,
				['scale'] = 1.0,
				['display'] = 1,
				['sprite'] = 108,
				['text'] = 'Safezone',
			},
		},
	},
```

```
        if v['zone']['type'] == 'poly' then
            zones[k] = lib.zones.poly({
                points = v['zone']['coords'],
                thickness = v['zone']['thickness'],
                debug = v['zone']['debug'],
                inside = v['zone']['action'].inside,
                onEnter = v['zone']['action'].onEnter,
                onExit = v['zone']['action'].onExit,
				typeZone = v['zone']['typezone']
            })
        elseif v['zone']['type'] == 'box' then
            zones[k] = lib.zones.box({
                coords = v['zone']['coords'][1],
                size = v['zone']['size'],
                rotation = v['zone']['rotation'],
                debug = v['zone']['debug'],
                inside = v['zone']['action'].inside,
                onEnter = v['zone']['action'].onEnter,
                onExit = v['zone']['action'].onExit,
				typeZone = v['zone']['typezone']
            })
        elseif v['zone']['type'] == 'sphere' then
            zones[k] = lib.zones.sphere({
                coords = v['zone']['coords'][1],
                radius = v['zone']['radius'],
                debug = v['zone']['debug'],
                inside = v['zone']['action'].inside,
                onEnter = v['zone']['action'].onEnter,
                onExit = v['zone']['action'].onExit,
				typeZone = v['zone']['typezone']
            })
        end
```

**Comment by mindiw01** [comment]
```
local points = {
		vector3(-877.025818, 5410.931152, 34.652859),
		vector3(-627.529846, 5555.611816, 39.498642),
		vector3(-428.088470, 5426.170898, 91.048416),
		vector3(-492.952026, 5195.912598, 146.900085),
	}
	lib.zones.poly({
		points = points,
		thickness = 200.0,
	})
```

**Comment by DokaDoka** [comment]
At a glance, Z values need to be the same

**Comment by thelindat** [comment]
> At a glance, Z values need to be the same

Wasn’t the point of this code to normalise the z?

**Comment by Moozdzn** [comment]
Are points not a vector2 and Z in a separate field because of backwards compatibility?

**Comment by DokaDoka** [comment]
still haven't been able to look at this, but no, there is no backwards compatibility

**Pull request closed without merging**
