### PR TITLE
radial opened / closed event

### PR DESCRIPTION
**Pull request by JonasDev17**
An event that gets triggered when the menu is opened or closed.
Could also be named onOpen / onClose or onShow / onHide, opened / hidden....

### CODE REVIEW

**Comment by TonybynMp4** [comment]
OMG that is revolutionnary thank you so much for this upgrade that will make the society a better place!

**Comment by ARSSANTO** [comment]
it will help us to add radial menu items from other script with condition

**Comment by thelindat** [comment]
Because brigading is what gets features accepted. 😒
Explain the actual use-case (without saying "well qb does it!"). Like hell I'm using that event name too.

> it will help us to add radial menu items from other script with condition

??????

**Comment by TonybynMp4** [comment]
> Because brigading is what gets features accepted. 😒 Explain the actual use-case (without saying "well qb does it!"). Like hell I'm using that event name too.

Basically without an event you have to loop while you're inside the zone to chekc if you got in or out of a car and stuff, that allows to not loop and just check when the menu is actually being opened

**Comment by ARSSANTO** [comment]
> Because brigading is what gets features accepted. 😒
> Explain the actual use-case (without saying "well qb does it!"). Like hell I'm using that event name too.
> 
> > it will help us to add radial menu items from other script with condition
> 
> ??????

you are smort already get why this pr opend 

if not ok so in qb there is a trigger event like onradialmenuopen  which are being registered so many other creator script  + jdevs qb garages 
therefor we can register the same event on client to manipulate sets of menu items through function #sorry for bad English its not my 1st language

**Comment by thelindat** [comment]
> Basically in our case without an event you have to loop while you're inside the zone to check if you got in or out of a car and stuff, that allows to not loop and just check when the menu is actually being opened, wich can be useful for other cases too

Triggering an event with 100 listeners for "radialopened" is worse than a slow loop anyway. Can also accomplish a lot using zones onEnter/onExit and cache.vehicle/lib.onCache.

> if not ok so in qb there is a trigger event like onradialmenuopen which are being registered so many other creator script + jdevs qb garages

> Explain the actual use-case (without saying "well qb does it!").

**Comment by thelindat** [comment]
Closed since you're all just being weirdos spamming comments "wow so good add this" and reacting with 👀 rather than giving me any reasonable use for this event.

**Comment by TonybynMp4** [comment]
> Closed since you're all just being weirdos spamming comments "wow so good add this" and reacting with 👀 rather than giving me any reasonable use for this event.

I mean after your last comment i had nothing more to say you provided a good solution lol

**Pull request closed without merging**
