### PR TITLE
feat(interface/textarea): min / max length for textarea

### PR DESCRIPTION
**Pull request by Tynopia**
Hello,

I've implemented a minimum or maximum length for the textarea to enhance the security of our data persistence.

image

### CODE REVIEW

**Comment by Tynopia** [comment]
Documentation: https://github.com/overextended/overextended.github.io/pull/186

**Comment by Tynopia** [comment]
@thelindat Is there something why nothing happens here

**Comment by Tynopia** [comment]
@LukeWasTakenn

**Comment by LukeWasTakenn** [comment]
I don't like the look of the native html validation tooltips so this is something that would have to wait for the improved form error handling for the input dialog in the future.

**Pull request closed without merging**
