### PR TITLE
feat(addCommand): Allow multiple groups

### PR DESCRIPTION
**Pull request by jag3dagster**
* Add ability to pass in a list of groups that can utilize the command being added

### CODE REVIEW

**Comment by thelindat** [comment]
Would be better to check if groups is a table and then iterate over the values, else use the current behaviour.

**Comment by jag3dagster** [comment]
Yeah, I was in a toss up over the two choices myself. I figured the overhead for the since element loop was relatively negligible, since it'll be repeated code in each block, but I'm okay with swapping to check instead of forcing it into a table.

**Comment by thelindat** [comment]
> I figured the overhead for the since element loop was relatively negligible

It is, but I try to avoid short-lived objects and ipairs when I can. It does simplify things though. A minor improvement over the current checks on line 41/42.
```lua
if type(group) ~= 'table' then
    group = { group or 'builtin.everyone' }
end
```

**Comment by jag3dagster** [comment]
> I try to avoid short-lived objects and ipairs when I can

Just out of curiosity, why do you avoid them? Just for cleanliness / readability? Or something else?

**Comment by thelindat** [comment]
I prefer the look of `for i` compared to `ipairs`, it can be more flexible, and makes it obvious the table should be an array.
Once you get into large tables it also becomes an optimisation thing, and I'd prefer to be consistent with how I iterate tables.

I avoid short-lived tables to avoid extra memory allocation and gc cycles.

Both of these are negligible in this situation since the function only executes once, rather than frequently called in a loop or something; but again, I like to be consistent.

**Pull request merged**
