### PR TITLE
feat(imports): get entities on server

### PR DESCRIPTION
**Pull request by Andyyy7666**
This is needed on the server

### CODE REVIEW

**Comment by Andyyy7666** [comment]
@LukeWasTakenn this is ready

**Comment by thelindat** [comment]
I'd rather not just see the code duplicated everywhere, i.e. adding a function to replicate `GetGamePool` on the server and then making most of the modules shared.

**Comment by Andyyy7666** [comment]
There would be a slight problem with a few functions such as the `getNearbyPlayers` one where you can include getting the player but on the server you'd want to get any player so that wouldn't make sense.

**Comment by thelindat** [comment]
> making most of the modules shared

or otherwise ignoring client-specific args.

**Comment by Andyyy7666** [comment]
Didn't merge getting player since that works differently on server

**Comment by Moozdzn** [comment]
I think you can use lib.context instead of multiple IsDuplicityVersion

**Comment by Andyyy7666** [comment]
> I think you can use lib.context instead of multiple IsDuplicityVersion

I don’t recall lib.context being a feature, can you give me an example of what you mean?

**Comment by Moozdzn** [comment]
https://github.com/overextended/ox_lib/blob/6c40dd2889cbc7edb153fe4a4e98143bc44f4fbd/init.lua#L89

**Comment by Andyyy7666** [comment]
Thank you I'll use that instead.

**Pull request merged**
