### PR TITLE
tweak(web): components for markdown headings

### PR DESCRIPTION
**Pull request by jellyton69**
Fixed weird heading margins when using markdown heading props.
August06 - 03 24 - 2641

### CODE REVIEW

**Review by LukeWasTakenn — CHANGES_REQUESTED** [review]
`markdowncomponents.tsx` file should follow the naming convention so far, `MarkdownComponents.tsx`

**Comment by jellyton69** [comment]
> `markdowncomponents.tsx` file should follow the naming convention so far, `MarkdownComponents.tsx`

I appended the original commit when I moved the changes to a new branch, so it's already changed. 👍

**Comment by LukeWasTakenn** [comment]
> > `markdowncomponents.tsx` file should follow the naming convention so far, `MarkdownComponents.tsx`
> 
> I appended the original commit when I moved the changes to a new branch, so it's already changed. 👍

But the file is still lowercase...?

image

**Comment by jellyton69** [comment]
> > > `markdowncomponents.tsx` file should follow the naming convention so far, `MarkdownComponents.tsx`
> > 
> > 
> > I appended the original commit when I moved the changes to a new branch, so it's already changed. 👍
> 
> But the file is still lowercase...?
> 
> image

Hmm, I see why that didn't update, github is not registering the file as an active change.
Code - August06 - 12 03 - 2642

**Review by LukeWasTakenn — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
