### PR TITLE
Hidden Context Button

### PR DESCRIPTION
**Pull request by Axel2222**
Adding option to hide the button from the context menu using the param "hidden"

### CODE REVIEW

**Comment by Moozdzn** [comment]
What is the use case for this? Can you simply not add that option to the menu?
To toggle this state you have to re-register the whole menu again, no?

**Comment by Axel2222** [comment]
For example, if you have one context menu with 10 options and you need to show only 3 of them, you can use hidden instead of using 'if' for every option. And the code will look much prettier.

**Comment by thelindat** [comment]
Prettier is subjective, and you still have to register the menu again while including the options you want hidden; seems a bit pointless.

**Comment by Moozdzn** [comment]
How do you determine if the option is supposed to be hidden or not without some type of condition

**Comment by LukeWasTakenn** [comment]
I myself really don't need the point of this, definitely don't see it justifying the code complexity that comes with it, either don't add the button in at all or use the `disabled` prop.

**Comment by Axel2222** [comment]
> Prettier is subjective, and you still have to register the menu again while including the options you want hidden; seems a bit pointless.

Don't you have to register the menu again if you want to disable the option?

**Comment by thelindat** [comment]
> Don't you have to register the menu again if you want to disable the option?

Yes. And to make options "hidden" you can just not have those options in the first place 🤯

**Pull request closed without merging**
